//
// Created by fexolm on 7/23/17.
//

#ifndef MATCHMAKINGCLIENT_MESSAGE_TYPES_H
#define MATCHMAKINGCLIENT_MESSAGE_TYPES_H

enum message_type {
    CREATE_ROOM,
    JOIN_ROOM,
    LEAVE_ROOM,
    START_GAME,
    SHOW_ROOMS,
    OPPONENT_LEAVED,
    ROOM_CLOSED,
    PLAYER_JOINED,
};

#endif //MATCHMAKINGCLIENT_MESSAGE_TYPES_H
